import { Prisma } from "@prisma/client"

export const monsterList: Prisma.MonsterCreateManyInput[] = [
  {
    originName: "Aaliyah",
    monsterName: "토템술사",
    elementType: "water",
    keyword: ["물", "물토템술사"],
  },
  {
    originName: "Abellio",
    monsterName: "드루이드",
    elementType: "water",
    keyword: ["물"],
  },
  {
    originName: "Abigail",
    monsterName: "캐논걸",
    elementType: "water",
    keyword: ["물", "물캐논"],
  },
  {
    originName: "Acasis",
    monsterName: "실피드",
    elementType: "wind",
    keyword: ["풍", "풍실피드"],
  },
  {
    originName: "Adrian",
    monsterName: "",
    elementType: "fire",
    keyword: ["불"],
  },
  {
    originName: "Adriana",
    monsterName: "",
    elementType: "water",
    keyword: ["물"],
  },
  {
    originName: "Aegir",
    monsterName: "야만용사",
    elementType: "water",
    keyword: ["물", "물야만용사"],
  },
  {
    originName: "Aeilene",
    monsterName: "페어리",
    elementType: "wind",
    keyword: ["풍", "풍페어리"],
  },
  {
    originName: "Ahman",
    monsterName: "베어맨",
    elementType: "light",
    keyword: ["빛", "빛베어맨"],
  },
  {
    originName: "Ahmed",
    monsterName: "",
    elementType: "light",
    keyword: ["빛"],
  },
  {
    originName: "Akhamamir",
    monsterName: "이프리트",
    elementType: "wind",
    keyword: ["풍", "풍이프리트"],
  },
  {
    originName: "Akia",
    monsterName: "서큐버스",
    elementType: "fire",
    keyword: ["불", "불서큐버스"],
  },
  {
    originName: "Akroma",
    monsterName: "발키리",
    elementType: "light",
    keyword: ["빛", "빛발키리"],
  },
  {
    originName: "Alexandra",
    monsterName: "유니콘",
    elementType: "dark",
    keyword: ["암", "암유니콘"],
  },
  {
    originName: "Alice",
    monsterName: "마카롱",
    elementType: "fire",
    keyword: ["불", "불마카롱"],
  },
  {
    originName: "Alicia",
    monsterName: "극지여왕",
    elementType: "water",
    keyword: ["물", "물극지여왕"],
  },
  {
    originName: "Altair",
    monsterName: "알타이어",
    elementType: "light",
    keyword: ["빛"],
  },
  {
    originName: "Amanda",
    monsterName: "마법궁사",
    elementType: "fire",
    keyword: ["불", "불마궁", "불마법궁사"],
  },
  {
    originName: "Amarna",
    monsterName: "아누비스",
    elementType: "light",
    keyword: ["빛", "빛아누비스"],
  },
  {
    originName: "Amber",
    monsterName: "배틀엔젤",
    elementType: "water",
    keyword: ["물", "물배틀엔젤"],
  },
  {
    originName: "Amduat",
    monsterName: "아누비스",
    elementType: "dark",
    keyword: ["암", "암아누비스"],
  },
  {
    originName: "Amelia",
    monsterName: "유니콘",
    elementType: "water",
    keyword: ["물", "물유니콘"],
  },
  {
    originName: "Anavel",
    monsterName: "오컬트",
    elementType: "water",
    keyword: ["물", "물오컬트"],
  },
  {
    originName: "Anduril",
    monsterName: "인페르노",
    elementType: "wind",
    keyword: ["풍", "풍인페르노"],
  },
  {
    originName: "Angela",
    monsterName: "푸딩공주",
    elementType: "wind",
    keyword: ["풍", "풍푸딩공주"],
  },
  {
    originName: "Anne",
    monsterName: "카우걸",
    elementType: "fire",
    keyword: ["불", "불카우걸"],
  },
  {
    originName: "Antares",
    monsterName: "리치",
    elementType: "fire",
    keyword: ["불", "불리치"],
  },
  {
    originName: "Aqcus",
    monsterName: "상어",
    elementType: "water",
    keyword: ["물", "물상어"],
  },
  {
    originName: "Aquila",
    monsterName: "브라우니",
    elementType: "wind",
    keyword: ["풍", "풍브라우니"],
  },
  {
    originName: "Arang",
    monsterName: "구미호",
    elementType: "wind",
    keyword: ["풍", "풍구미호"],
  },
  {
    originName: "Ardella",
    monsterName: "마법궁사",
    elementType: "wind",
    keyword: ["풍", "풍마궁", "풍마법궁사"],
  },
  {
    originName: "Argen",
    monsterName: "마법궁사",
    elementType: "wind",
    keyword: ["풍", "풍마궁", "풍마법궁사"],
  },
  { originName: "Aria", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ariana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ariel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Arkajan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Arnold", monsterName: "", elementType: null, keyword: [] },
  { originName: "Artamiel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Aschubel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ashour", monsterName: "", elementType: null, keyword: [] },
  { originName: "Asima", monsterName: "", elementType: null, keyword: [] },
  { originName: "Astar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Astrid", monsterName: "", elementType: null, keyword: [] },
  { originName: "Atenai", monsterName: "", elementType: null, keyword: [] },
  { originName: "Audrey", monsterName: "", elementType: null, keyword: [] },
  { originName: "Aurelia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Avaris", monsterName: "", elementType: null, keyword: [] },
  { originName: "Baekdu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bael", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bagir", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bailey", monsterName: "", elementType: null, keyword: [] },
  { originName: "Baleygr", monsterName: "", elementType: null, keyword: [] },
  { originName: "Barbara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Baretta", monsterName: "", elementType: null, keyword: [] },
  { originName: "Barque", monsterName: "", elementType: null, keyword: [] },
  { originName: "Basalt", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bastet", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bayek-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bayek-F", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bayek-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bayek-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bayek-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Beelzebub", monsterName: "", elementType: null, keyword: [] },
  { originName: "Belial", monsterName: "", elementType: null, keyword: [] },
  { originName: "Belita", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bella", monsterName: "", elementType: null, keyword: [] },
  { originName: "Belladeon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bellenus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Benedict", monsterName: "", elementType: null, keyword: [] },
  { originName: "Berenice", monsterName: "", elementType: null, keyword: [] },
  { originName: "Berghild", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bering", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bernadotte", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bernard", monsterName: "", elementType: null, keyword: [] },
  { originName: "Beth", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bethony", monsterName: "", elementType: null, keyword: [] },
  { originName: "Betta", monsterName: "", elementType: null, keyword: [] },
  { originName: "Birman", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bloodya", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bolverk", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bombay", monsterName: "", elementType: null, keyword: [] },
  { originName: "Borgnine", monsterName: "", elementType: null, keyword: [] },
  { originName: "Brandia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Briand", monsterName: "", elementType: null, keyword: [] },
  { originName: "Brig", monsterName: "", elementType: null, keyword: [] },
  { originName: "Brita", monsterName: "", elementType: null, keyword: [] },
  { originName: "Bulldozer", monsterName: "", elementType: null, keyword: [] },
  { originName: "Burentau", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cadiz", monsterName: "", elementType: null, keyword: [] },
  { originName: "Calicus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Camaryn", monsterName: "", elementType: null, keyword: [] },
  { originName: "Camilla", monsterName: "", elementType: null, keyword: [] },
  { originName: "Camules", monsterName: "", elementType: null, keyword: [] },
  { originName: "Carbine", monsterName: "", elementType: null, keyword: [] },
  { originName: "Carcano", monsterName: "", elementType: null, keyword: [] },
  { originName: "Carlos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Carrack", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cassie", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cayde", monsterName: "", elementType: null, keyword: [] },
  { originName: "Celia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Celine", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ceres", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chacha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chakra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chamie", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chamomile", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chandra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Charlotte", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chasun", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cheongpung", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cheryl", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chichi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chilling", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chiwu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chloe", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chow", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chris", monsterName: "", elementType: null, keyword: [] },
  { originName: "Christina", monsterName: "", elementType: null, keyword: [] },
  { originName: "ChunLi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chunli-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chunli-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chunli-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Chunli-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cichlid", monsterName: "", elementType: null, keyword: [] },
  { originName: "Claire", monsterName: "", elementType: null, keyword: [] },
  { originName: "Clara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Coco", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cogma", monsterName: "", elementType: null, keyword: [] },
  { originName: "Conrad", monsterName: "", elementType: null, keyword: [] },
  { originName: "Copper", monsterName: "", elementType: null, keyword: [] },
  { originName: "Cordelia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Covenant", monsterName: "", elementType: null, keyword: [] },
  { originName: "Craig", monsterName: "", elementType: null, keyword: [] },
  { originName: "Craka", monsterName: "", elementType: null, keyword: [] },
  { originName: "Crane", monsterName: "", elementType: null, keyword: [] },
  { originName: "Crawler", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dagora", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dagorr", monsterName: "", elementType: null, keyword: [] },
  { originName: "Daharenos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Daniel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Danu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Daphnis", monsterName: "", elementType: null, keyword: [] },
  { originName: "Darion", monsterName: "", elementType: null, keyword: [] },
  { originName: "Deborah", monsterName: "", elementType: null, keyword: [] },
  { originName: "Decamaron", monsterName: "", elementType: null, keyword: [] },
  { originName: "Delphoi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Destiny", monsterName: "", elementType: null, keyword: [] },
  { originName: "Deva", monsterName: "", elementType: null, keyword: [] },
  { originName: "Devaraja", monsterName: "", elementType: null, keyword: [] },
  { originName: "Devinodon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dhalsim-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dhalsim-F", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dhalsim-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dhalsim-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dhalsim-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Diana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dias", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dominic", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dona", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dongbaek", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dorothy", monsterName: "", elementType: null, keyword: [] },
  { originName: "Douglas", monsterName: "", elementType: null, keyword: [] },
  { originName: "Douman", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dova", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dover", monsterName: "", elementType: null, keyword: [] },
  { originName: "Draco", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dragunov", monsterName: "", elementType: null, keyword: [] },
  { originName: "Driller", monsterName: "", elementType: null, keyword: [] },
  { originName: "Drogan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Duamutef", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dusky", monsterName: "", elementType: null, keyword: [] },
  { originName: "Dyeus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Einheri", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eintau", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eirgar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eivor-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eivor-F", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eivor-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eivor-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eivor-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eladriel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eleanor", monsterName: "", elementType: null, keyword: [] },
  { originName: "Elena", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eleni", monsterName: "", elementType: null, keyword: [] },
  { originName: "Elenoa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ella", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ellena", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ellin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Elpuria", monsterName: "", elementType: null, keyword: [] },
  { originName: "Elsharion", monsterName: "", elementType: null, keyword: [] },
  { originName: "Elucia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eludain", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eludia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eluin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Emily", monsterName: "", elementType: null, keyword: [] },
  { originName: "Emma", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eredas", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ermeda", monsterName: "", elementType: null, keyword: [] },
  { originName: "Erwin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eshir", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "EspressoCookie-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "EspressoCookie-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "EspressoCookie-L",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "EspressoCookie-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "EspressoCookie-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Ethna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Eva", monsterName: "", elementType: null, keyword: [] },
  { originName: "Evan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ezio-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ezio-F", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ezio-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ezio-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ezio-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fairo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fami", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fao", monsterName: "", elementType: null, keyword: [] },
  { originName: "Federica", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fedora", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fei", monsterName: "", elementType: null, keyword: [] },
  { originName: "Felleria", monsterName: "", elementType: null, keyword: [] },
  { originName: "FengYan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fermion", monsterName: "", elementType: null, keyword: [] },
  { originName: "Figaro", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fran", monsterName: "", elementType: null, keyword: [] },
  { originName: "Frederic", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fria", monsterName: "", elementType: null, keyword: [] },
  { originName: "Frigate", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fuco", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fudge", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fuuki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Fynn", monsterName: "", elementType: null, keyword: [] },
  { originName: "Galleon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gamir", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ganache", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gangchun", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ganymede", monsterName: "", elementType: null, keyword: [] },
  { originName: "Garo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Garoche", monsterName: "", elementType: null, keyword: [] },
  { originName: "Garok", monsterName: "", elementType: null, keyword: [] },
  { originName: "Geldnir", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gemini", monsterName: "", elementType: null, keyword: [] },
  { originName: "Geoffrey", monsterName: "", elementType: null, keyword: [] },
  { originName: "Giana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gildong", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gina", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "GingerBrave",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Giou", monsterName: "", elementType: null, keyword: [] },
  { originName: "Giselle", monsterName: "", elementType: null, keyword: [] },
  { originName: "Glinodon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gorgo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Granite", monsterName: "", elementType: null, keyword: [] },
  { originName: "Grego", monsterName: "", elementType: null, keyword: [] },
  { originName: "Grogen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Groggo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Grotau", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gruda", monsterName: "", elementType: null, keyword: [] },
  { originName: "Guillaume", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gunpyeong", monsterName: "", elementType: null, keyword: [] },
  { originName: "Gurkha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Haegang", monsterName: "", elementType: null, keyword: [] },
  { originName: "Haken", monsterName: "", elementType: null, keyword: [] },
  { originName: "Halphas", monsterName: "", elementType: null, keyword: [] },
  { originName: "Han", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hannah", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hanra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hanwul", monsterName: "", elementType: null, keyword: [] },
  { originName: "Harmonia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hathor", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hector", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hekerson", monsterName: "", elementType: null, keyword: [] },
  { originName: "Helena", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hellea", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hemos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Herne", monsterName: "", elementType: null, keyword: [] },
  { originName: "Herteit", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hibiscus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hiro", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hiva", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "Hollyberry Cookie-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "HollyberryCookie-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "HollyberryCookie-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "HollyberryCookie-L",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "HollyberryCookie-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Homunculus-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Homunculus-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Homunculus-L",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Homunculus-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Homunculus-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "HongHua", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hongyeon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Howl", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hraesvelg", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hrungnir", monsterName: "", elementType: null, keyword: [] },
  { originName: "Huan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Huga", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hwa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hwadam", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hwahee", monsterName: "", elementType: null, keyword: [] },
  { originName: "Hyanes", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ian", monsterName: "", elementType: null, keyword: [] },
  { originName: "Icares", monsterName: "", elementType: null, keyword: [] },
  { originName: "Icaru", monsterName: "", elementType: null, keyword: [] },
  { originName: "Icasha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Igmanodon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ignicus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Illianna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Imesety", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "ImpChampion-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "ImpChampion-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "ImpChampion-L",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "ImpChampion-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "ImpChampion-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Iona", monsterName: "", elementType: null, keyword: [] },
  { originName: "Irene", monsterName: "", elementType: null, keyword: [] },
  { originName: "Iris", monsterName: "", elementType: null, keyword: [] },
  { originName: "Iron", monsterName: "", elementType: null, keyword: [] },
  { originName: "Isabelle", monsterName: "", elementType: null, keyword: [] },
  { originName: "Isael", monsterName: "", elementType: null, keyword: [] },
  { originName: "Iselia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Isillen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Isis", monsterName: "", elementType: null, keyword: [] },
  { originName: "Iunu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Izaria", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jaara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jackie", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jackson", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jade", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jager", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jamie", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jamire", monsterName: "", elementType: null, keyword: [] },
  { originName: "Janssen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jansson", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jarrett", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jasmine", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jean", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jeanne", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jeogun", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jessica", monsterName: "", elementType: null, keyword: [] },
  { originName: "John", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jojo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Josephine", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jubelle", monsterName: "", elementType: null, keyword: [] },
  { originName: "Julianne", monsterName: "", elementType: null, keyword: [] },
  { originName: "Julie", monsterName: "", elementType: null, keyword: [] },
  { originName: "Julien", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jultan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jumaline", monsterName: "", elementType: null, keyword: [] },
  { originName: "Jun", monsterName: "", elementType: null, keyword: [] },
  { originName: "Juno", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kabilla", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kacey", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kahli", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kahn", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kaien", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kaimann", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kaito", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kaki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kalantatze", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kamatau", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kamiya", monsterName: "", elementType: null, keyword: [] },
  { originName: "Karakum", monsterName: "", elementType: null, keyword: [] },
  { originName: "Karl", monsterName: "", elementType: null, keyword: [] },
  { originName: "Karnal", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kashmir", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "Kassandra-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Kassandra-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Kassandra-L",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Kassandra-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "Kassandra-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Katarina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kaz", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ken", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kernodon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Khmun", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kiara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kiki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kinki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Konamiya", monsterName: "", elementType: null, keyword: [] },
  { originName: "Korona", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kovarci", monsterName: "", elementType: null, keyword: [] },
  { originName: "Krakdon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kro", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kroa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kugo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kuhn", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kumae", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kumar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kuna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kunda", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kungen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kunite", monsterName: "", elementType: null, keyword: [] },
  { originName: "Kyle", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lagmaron", monsterName: "", elementType: null, keyword: [] },
  { originName: "Laika", monsterName: "", elementType: null, keyword: [] },
  { originName: "Laima", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lala", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lanett", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lapis", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lariel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lavender", monsterName: "", elementType: null, keyword: [] },
  { originName: "Layla", monsterName: "", elementType: null, keyword: [] },
  { originName: "Leah", monsterName: "", elementType: null, keyword: [] },
  { originName: "Leo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Leona", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lexy", monsterName: "", elementType: null, keyword: [] },
  { originName: "Liam", monsterName: "", elementType: null, keyword: [] },
  { originName: "Liebli", monsterName: "", elementType: null, keyword: [] },
  { originName: "Liesel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Liliana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Linda", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lindermen", monsterName: "", elementType: null, keyword: [] },
  { originName: "LingLing", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lionel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lisa", monsterName: "", elementType: null, keyword: [] },
  { originName: "LiuMei", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Logan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Loque", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lora", monsterName: "", elementType: null, keyword: [] },
  { originName: "Loren", monsterName: "", elementType: null, keyword: [] },
  { originName: "Louis", monsterName: "", elementType: null, keyword: [] },
  { originName: "Louise", monsterName: "", elementType: null, keyword: [] },
  { originName: "Luan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lucas", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lucasha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lucia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lucien", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lucifer", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ludo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Luer", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lukan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lumirecia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Luna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lupinus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lusha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lushen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lydia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Lyn", monsterName: "", elementType: null, keyword: [] },
  { originName: "Madeleine", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "MadeleineCookie-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "MadeleineCookie-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "MadeleineCookie-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "MadeleineCookie-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Maggi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Magnum", monsterName: "", elementType: null, keyword: [] },
  { originName: "Malaka", monsterName: "", elementType: null, keyword: [] },
  { originName: "Malite", monsterName: "", elementType: null, keyword: [] },
  { originName: "Manannan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Manon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mantura", monsterName: "", elementType: null, keyword: [] },
  { originName: "Manx", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mao", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Marble", monsterName: "", elementType: null, keyword: [] },
  { originName: "Martina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Maruna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Masha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mav", monsterName: "", elementType: null, keyword: [] },
  { originName: "Maximilian", monsterName: "", elementType: null, keyword: [] },
  { originName: "Maya", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mayasura", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mbison-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mbison-F", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mbison-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mbison-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mbison-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Megan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mei", monsterName: "", elementType: null, keyword: [] },
  { originName: "MeiHouWang", monsterName: "", elementType: null, keyword: [] },
  { originName: "Melissa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mellia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mephisto", monsterName: "", elementType: null, keyword: [] },
  { originName: "MiYing", monsterName: "", elementType: null, keyword: [] },
  { originName: "Michelle", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mihael", monsterName: "", elementType: null, keyword: [] },
  { originName: "Miho", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mihyang", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mikene", monsterName: "", elementType: null, keyword: [] },
  { originName: "Miles", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mimirr", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Minato", monsterName: "", elementType: null, keyword: [] },
  { originName: "Miriam", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mirinae", monsterName: "", elementType: null, keyword: [] },
  { originName: "Misty", monsterName: "", elementType: null, keyword: [] },
  { originName: "Molly", monsterName: "", elementType: null, keyword: [] },
  { originName: "Molong", monsterName: "", elementType: null, keyword: [] },
  { originName: "Momo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Monte", monsterName: "", elementType: null, keyword: [] },
  { originName: "Mookwol", monsterName: "", elementType: null, keyword: [] },
  { originName: "Moore", monsterName: "", elementType: null, keyword: [] },
  { originName: "Moria", monsterName: "", elementType: null, keyword: [] },
  { originName: "Morris", monsterName: "", elementType: null, keyword: [] },
  { originName: "Naki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Namib", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nangrim", monsterName: "", elementType: null, keyword: [] },
  { originName: "Naomi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Narsha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Natalie", monsterName: "", elementType: null, keyword: [] },
  { originName: "Neal", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nebelung", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nephthys", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nickel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nicki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nigong", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nisha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nora", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nubia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Nyx", monsterName: "", elementType: null, keyword: [] },
  { originName: "Oberon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Odin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Okeanos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Oliver", monsterName: "", elementType: null, keyword: [] },
  { originName: "Olivia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Olivine", monsterName: "", elementType: null, keyword: [] },
  { originName: "Omar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ongyouki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Onyx", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ophilia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Orion", monsterName: "", elementType: null, keyword: [] },
  { originName: "Orochi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Pang", monsterName: "", elementType: null, keyword: [] },
  { originName: "Parjanya", monsterName: "", elementType: null, keyword: [] },
  { originName: "Pater", monsterName: "", elementType: null, keyword: [] },
  { originName: "Patrick", monsterName: "", elementType: null, keyword: [] },
  { originName: "Pave", monsterName: "", elementType: null, keyword: [] },
  { originName: "Perna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Phenaka", monsterName: "", elementType: null, keyword: [] },
  { originName: "Pigma", monsterName: "", elementType: null, keyword: [] },
  { originName: "Platy", monsterName: "", elementType: null, keyword: [] },
  { originName: "Pontos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Poseidon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Praha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Praline", monsterName: "", elementType: null, keyword: [] },
  { originName: "Prilea", monsterName: "", elementType: null, keyword: [] },
  { originName: "Priz", monsterName: "", elementType: null, keyword: [] },
  { originName: "Prom", monsterName: "", elementType: null, keyword: [] },
  { originName: "Psamathe", monsterName: "", elementType: null, keyword: [] },
  { originName: "Pungbaek", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "PureVanilla Cookie-F",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "PureVanilla Cookie-WA",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "PureVanillaCookie-D",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "PureVanillaCookie-L",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "PureVanillaCookie-W",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Purian", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "Qebehsenuef",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  {
    originName: "QitianDasheng",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "ROBO-E65", monsterName: "", elementType: null, keyword: [] },
  { originName: "ROBO-F29", monsterName: "", elementType: null, keyword: [] },
  { originName: "ROBO-G92", monsterName: "", elementType: null, keyword: [] },
  { originName: "ROBO-P27", monsterName: "", elementType: null, keyword: [] },
  { originName: "ROBO-R40", monsterName: "", elementType: null, keyword: [] },
  { originName: "Racuni", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ragdoll", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ragion", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rahul", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rakaja", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rakan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Raki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ralph", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ramagos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ramahan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ramira", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ran", monsterName: "", elementType: null, keyword: [] },
  { originName: "Randy", monsterName: "", elementType: null, keyword: [] },
  { originName: "Raoq", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rasheed", monsterName: "", elementType: null, keyword: [] },
  { originName: "Raviti", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rebecca", monsterName: "", elementType: null, keyword: [] },
  { originName: "Remy", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ren", monsterName: "", elementType: null, keyword: [] },
  { originName: "Reno", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rica", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rigel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Riley", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ritesh", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ritsu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rizak", monsterName: "", elementType: null, keyword: [] },
  { originName: "Roger", monsterName: "", elementType: null, keyword: [] },
  { originName: "Roid", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rosemary", monsterName: "", elementType: null, keyword: [] },
  { originName: "Rumicus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ryan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ryu-D", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ryu-F", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ryu-L", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ryu-W", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ryu-WA", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sabrina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sagar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sahara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Salah", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sath", monsterName: "", elementType: null, keyword: [] },
  { originName: "Savannah", monsterName: "", elementType: null, keyword: [] },
  { originName: "Scarlett", monsterName: "", elementType: null, keyword: [] },
  { originName: "Seal", monsterName: "", elementType: null, keyword: [] },
  { originName: "Seara", monsterName: "", elementType: null, keyword: [] },
  { originName: "Seimei", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sekhmet", monsterName: "", elementType: null, keyword: [] },
  { originName: "Selena", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sera", monsterName: "", elementType: null, keyword: [] },
  { originName: "Seren", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shahat", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shailoq", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shaina", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shakan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shamann", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shamar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shannon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sharman", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sharron", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shazam", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shihou", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shihwa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shimitae", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shizuka", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shren", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shumar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shun", monsterName: "", elementType: null, keyword: [] },
  { originName: "Shushu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Siamese", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sian", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sieq", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sige", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sigmarus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sigrid", monsterName: "", elementType: null, keyword: [] },
  { originName: "Silia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Silver", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sisroo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Skogul", monsterName: "", elementType: null, keyword: [] },
  { originName: "Smicer", monsterName: "", elementType: null, keyword: [] },
  { originName: "Smokey", monsterName: "", elementType: null, keyword: [] },
  { originName: "Soha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Solveig", monsterName: "", elementType: null, keyword: [] },
  {
    originName: "SonZhangLao",
    monsterName: "",
    elementType: null,
    keyword: [],
  },
  { originName: "Songseol", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sonia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sonnet", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sonora", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sophia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sorin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Spectra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Stella", monsterName: "", elementType: null, keyword: [] },
  { originName: "Su", monsterName: "", elementType: null, keyword: [] },
  { originName: "Suiki", monsterName: "", elementType: null, keyword: [] },
  { originName: "Suri", monsterName: "", elementType: null, keyword: [] },
  { originName: "Surtr", monsterName: "", elementType: null, keyword: [] },
  { originName: "Susan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Susano", monsterName: "", elementType: null, keyword: [] },
  { originName: "Sylvia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tablo", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tagaros", monsterName: "", elementType: null, keyword: [] },
  { originName: "Talc", monsterName: "", elementType: null, keyword: [] },
  { originName: "Talia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Talisman", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tantra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tanya", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tanzaite", monsterName: "", elementType: null, keyword: [] },
  { originName: "Taor", monsterName: "", elementType: null, keyword: [] },
  { originName: "Taranys", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tarq", monsterName: "", elementType: null, keyword: [] },
  { originName: "Taru", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tatu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Taurus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Teon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tesarion", monsterName: "", elementType: null, keyword: [] },
  { originName: "Teshar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tetra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Thebae", monsterName: "", elementType: null, keyword: [] },
  { originName: "Theomars", monsterName: "", elementType: null, keyword: [] },
  { originName: "Thomas", monsterName: "", elementType: null, keyword: [] },
  { originName: "Thrain", monsterName: "", elementType: null, keyword: [] },
  { originName: "TianLang", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tiana", monsterName: "", elementType: null, keyword: [] },
  { originName: "TienQin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tilasha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Todd", monsterName: "", elementType: null, keyword: [] },
  { originName: "Toma", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tomoe", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tosi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tractor", monsterName: "", elementType: null, keyword: [] },
  { originName: "Trasar", monsterName: "", elementType: null, keyword: [] },
  { originName: "Trevor", monsterName: "", elementType: null, keyword: [] },
  { originName: "Triana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Trinity", monsterName: "", elementType: null, keyword: [] },
  { originName: "Triton", monsterName: "", elementType: null, keyword: [] },
  { originName: "Truffle", monsterName: "", elementType: null, keyword: [] },
  { originName: "Tyron", monsterName: "", elementType: null, keyword: [] },
  { originName: "Ursha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Urtau", monsterName: "", elementType: null, keyword: [] },
  { originName: "Usha", monsterName: "", elementType: null, keyword: [] },
  { originName: "Valantis", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vancliffe", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vanessa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Varuna", monsterName: "", elementType: null, keyword: [] },
  { originName: "Varus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vegabond", monsterName: "", elementType: null, keyword: [] },
  { originName: "Velajuel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Velfinodon", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vendhan", monsterName: "", elementType: null, keyword: [] },
  { originName: "Verad", monsterName: "", elementType: null, keyword: [] },
  { originName: "Verdehile", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vereesa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Veromos", monsterName: "", elementType: null, keyword: [] },
  { originName: "Veronica", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vidurr", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vigor", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vivachel", monsterName: "", elementType: null, keyword: [] },
  { originName: "Vritra", monsterName: "", elementType: null, keyword: [] },
  { originName: "Walkers", monsterName: "", elementType: null, keyword: [] },
  { originName: "Walter", monsterName: "", elementType: null, keyword: [] },
  { originName: "Wayne", monsterName: "", elementType: null, keyword: [] },
  { originName: "Wedjat", monsterName: "", elementType: null, keyword: [] },
  { originName: "WeiShin", monsterName: "", elementType: null, keyword: [] },
  { originName: "Windy", monsterName: "", elementType: null, keyword: [] },
  { originName: "Wolyung", monsterName: "", elementType: null, keyword: [] },
  { originName: "Woochi", monsterName: "", elementType: null, keyword: [] },
  { originName: "Woonhak", monsterName: "", elementType: null, keyword: [] },
  { originName: "Woonsa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Woosa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Xiana", monsterName: "", elementType: null, keyword: [] },
  { originName: "Xiao-Lin", monsterName: "", elementType: null, keyword: [] },
  { originName: "XiaoChun", monsterName: "", elementType: null, keyword: [] },
  { originName: "XiaoLing", monsterName: "", elementType: null, keyword: [] },
  { originName: "XingZhe", monsterName: "", elementType: null, keyword: [] },
  { originName: "XiongFei", monsterName: "", elementType: null, keyword: [] },
  { originName: "Yaku", monsterName: "", elementType: null, keyword: [] },
  { originName: "Yen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Yeonhong", monsterName: "", elementType: null, keyword: [] },
  { originName: "Yeonhwa", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zaiross", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zen", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zenisek", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zenobia", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zephicus", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zerath", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zeratu", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zibala", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zibrolta", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zima", monsterName: "", elementType: null, keyword: [] },
  { originName: "Zinc", monsterName: "", elementType: null, keyword: [] },
]
